apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPReadOnlyRootFilesystem
metadata:
  name: psp-readonlyrootfilesystem
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    excludedPods:
      - "test;root-fs-pod-allowed"
      - "kube-system;coredns-64897985d-" # has root fs by default
      - "kube-system;etcd-minikube" # has root fs by default
      - "kube-system;kube-apiserver-minikube" # has root fs by default
      - "kube-system;kube-controller-manager-minikube" # has root fs by default
      - "kube-system;kube-proxy-" # has root fs by default
      - "kube-system;kube-scheduler-minikube" # has root fs by default
      - "kube-system;storage-provisioner" # has root fs by default
    #exemptImages: ["k8s.gcr.io/etcd:*", "k8s.gcr.io/kube-apiserver:*", "k8s.gcr.io/kube-controller-manager:*", "k8s.gcr.io/kube-proxy:*", "k8s.gcr.io/kube-scheduler:*", "gcr.io/k8s-minikube/storage-provisioner:*"]
